# Generated by Django 5.1.4 on 2024-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=200, null=True)),
                ('adminpassword', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
