# Generated by Django 5.1.4 on 2024-12-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('product_image', models.ImageField(upload_to='')),
                ('top_view', models.ImageField(upload_to='')),
                ('right_side_view', models.ImageField(upload_to='')),
                ('left_side_view', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='videos/')),
                ('product_color1', models.CharField(max_length=20)),
                ('product_color2', models.CharField(max_length=20)),
                ('product_color3', models.CharField(max_length=20)),
                ('product_color4', models.CharField(max_length=20)),
                ('about_product', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
