# Generated by Django 5.1.4 on 2024-12-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='left_side_view',
            field=models.ImageField(blank=True, null=True, upload_to='products/frontimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/frontimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='right_side_view',
            field=models.ImageField(blank=True, null=True, upload_to='products/frontimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_view',
            field=models.ImageField(blank=True, null=True, upload_to='products/frontimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
